"""added foreign key to app_user and user

Revision ID: 2fd35240aaf6
Revises: 3e1854417a65
Create Date: 2026-06-05 12:25:25.042931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd35240aaf6'
down_revision: Union[str, Sequence[str], None] = '3e1854417a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('app_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'app_users', ['app_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'app_user_id')
    # ### end Alembic commands ###
