"""initial schema

Revision ID: 916df3ddff9a
Revises: 
Create Date: 2026-06-13 08:26:32.223831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '916df3ddff9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('curr_rating', sa.Integer(), nullable=True),
    sa.Column('max_rating', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('max_rank', sa.String(), nullable=True),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle')
    )
    op.create_table('contest_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('contest_name', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('old_rating', sa.Integer(), nullable=True),
    sa.Column('new_rating', sa.Integer(), nullable=True),
    sa.Column('problems_solved', sa.Integer(), nullable=True),
    sa.Column('unsolved_upsolvable_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contest_id')
    )
    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('problems_attempted', sa.Integer(), nullable=True),
    sa.Column('problems_solved', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Integer(), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('contest_participated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date')
    )
    op.create_table('problem_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('problem_index', sa.String(), nullable=True),
    sa.Column('problem_name', sa.String(), nullable=True),
    sa.Column('problem_rating', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('tags_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('recommendation_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_contest_id', sa.Integer(), nullable=True),
    sa.Column('problem_index', sa.String(), nullable=True),
    sa.Column('recommendation_type', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recommendation_type', 'problem_contest_id', 'problem_index')
    )
    op.create_table('skill_estimate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.Column('estimated_rating', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('trend', sa.Float(), nullable=True),
    sa.Column('last_computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.Column('total_attempted', sa.Integer(), nullable=True),
    sa.Column('total_solved', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_problem_rating', sa.Float(), nullable=True),
    sa.Column('hardest_solved_rating', sa.Integer(), nullable=True),
    sa.Column('weakness_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tag_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_performance')
    op.drop_table('skill_estimate')
    op.drop_table('recommendation_queue')
    op.drop_table('problem_attempt')
    op.drop_table('daily_activity')
    op.drop_table('contest_performance')
    op.drop_table('users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
